// SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"flag"
	"fmt"
	"io"
	"strings"
)

// completion prints a completion script generated from the flag set, so
// the scripts list every flag and cannot drift from --help.
func completion(fs *flag.FlagSet, shell string, stdout, stderr io.Writer) int {
	var names []string
	var fishLines []string
	fs.VisitAll(func(f *flag.Flag) {
		names = append(names, "--"+f.Name)
		fishLines = append(fishLines, fmt.Sprintf("complete -c passmcp-lsp -l %s -d %s", f.Name, fishQuote(f.Usage)))
	})
	var script string
	switch shell {
	case "bash":
		script = fmt.Sprintf(bashTemplate, strings.Join(names, " "))
	case "zsh":
		script = fmt.Sprintf(zshTemplate, strings.Join(names, " "))
	case "fish":
		script = "complete -c passmcp-lsp -f -n '__fish_use_subcommand' -a check -d 'check files and print what is wrong'\n" +
			strings.Join(fishLines, "\n") + "\n"
	default:
		_, _ = fmt.Fprintf(stderr, "passmcp-lsp: --completion %q: bash, zsh or fish\n", shell)
		return 2
	}
	_, _ = io.WriteString(stdout, script)
	return 0
}

func fishQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", `\'`) + "'" }

const bashTemplate = `# bash completion for passmcp-lsp, generated by passmcp-lsp --completion bash
_passmcp_lsp() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  if [ "${COMP_CWORD}" -eq 1 ] && [[ "${cur}" != -* ]]; then
    COMPREPLY=($(compgen -W "check" -- "${cur}"))
    return
  fi
  if [ "${COMP_WORDS[1]}" = "check" ]; then
    if [[ "${cur}" == -* ]]; then COMPREPLY=($(compgen -W "--output" -- "${cur}")); else COMPREPLY=($(compgen -f -- "${cur}")); fi
    return
  fi
  COMPREPLY=($(compgen -W "%s" -- "${cur}"))
}
complete -o default -F _passmcp_lsp passmcp-lsp
`

const zshTemplate = `#compdef passmcp-lsp
# zsh completion for passmcp-lsp, generated by passmcp-lsp --completion zsh
_passmcp_lsp() {
  if (( CURRENT == 2 )) && [[ ${words[CURRENT]} != -* ]]; then
    compadd check
    return
  fi
  if [[ ${words[2]} == check ]]; then
    _arguments '--output[output format]:format:(text json)' '*:file:_files'
    return
  fi
  compadd -- %s
}
compdef _passmcp_lsp passmcp-lsp
`
